[project]
name = "python-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.2.1",
 "qrcode>=8.1",
 "requests>=2.32.3",
 "watchdog>=6.0.0",
]
